- name: install strongswan
  apt:
    name:
    - strongswan
    - libcharon-extra-plugins
    state: latest

- name: configure strongswan
  template:
    src: ipsec.conf.j2
    dest: "/etc/ipsec.conf"
    backup: yes
  notify:
  - restart ipsec

- name: configure strongswan secrets
  lineinfile:
    path: "/etc/ipsec.secrets"
    line: "{{ inventory_hostname }} : RSA \"/etc/ipsec.d/private/vpn-server-key.pem\"" 
  notify:
  - restart ipsec

- name: configure strongswan secrets 2
  lineinfile:
    path: "/etc/ipsec.secrets"
    line: "#iPhone1 %any% : EAP \"Password1\""

- name: configure strongswan kernel ipsec
  lineinfile:
    path: /etc/strongswan.d/charon/kernel-libipsec.conf
    regexp: 'load = *'
    line: 'load = no'
  notify:
  - restart ipsec

